
name: skauthd.build
on:
- push

jobs:
  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: skauthd-macos
          path: ./target/release/skauthd
  build-musl-matrix:
    name: Build (Musl Matrix)
    strategy:
      matrix:
        platform: [
          { target: "aarch64-unknown-linux-musl", image_tag: "aarch64-musl", docker_namespace: "messense" },
          { target: "armv7-unknown-linux-musleabihf", image_tag: "armv7-musleabihf", docker_namespace: "benfred" },
          { target: "i586-unknown-linux-musl", image_tag: "i586-musl", docker_namespace: "messense" },
          { target: "x86_64-unknown-linux-musl", image_tag: "x86_64-musl", docker_namespace: "messense" },
        ]
    runs-on: ubuntu-latest
    container:
      image: docker://${{ matrix.platform.docker_namespace }}/rust-musl-cross:${{ matrix.platform.image_tag }}
      env:
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: skauthd-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/skauthd
